name: countrylens
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.2.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.1
  flutter_native_splash: ^2.4.6


icons_launcher:
  image_path: "assets/images/icons8-america-48.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  fonts:
    - family: Axiforma
      fonts:
        - asset: assets/axiforma_fonts/Axiforma-Heavy.ttf
          weight: 900
        - asset: assets/axiforma_fonts/Axiforma-Black.ttf
          weight: 800
        - asset: assets/axiforma_fonts/Axiforma-ExtraBold.ttf
          weight: 700
        - asset: assets/axiforma_fonts/Axiforma-Bold.ttf
          weight: 600
        - asset: assets/axiforma_fonts/Axiforma-SemiBold.ttf
          weight: 500
        - asset: assets/axiforma_fonts/Axiforma-Medium.ttf
          weight: 400
        - asset: assets/axiforma_fonts/Axiforma-Regular.ttf
          weight: 300
        - asset: assets/axiforma_fonts/Axiforma-Light.ttf
          weight: 200
        - asset: assets/axiforma_fonts/Axiforma-Thin.ttf
          weight: 100

flutter_native_splash:
  image: assets/images/splash_icon.png
  color: "#000000"

  android_12:
    image: "assets/images/splash_icon.png"
    color: "#000000"